"""Home page content for AI Analytics Assistant."""

WELCOME_TITLE = "AI Analytics Assistant"

WELCOME_INTRO = """
Welcome to the **AI Analytics Assistant**, your intelligent companion for exploring and understanding your data analysis results.

This application provides a user-friendly interface for browsing analysis artifacts generated by the Analyst Agent engine. 
All analyses are **deterministic and reproducible** — the same data always produces the same insights.
"""

TAB_DESCRIPTIONS = """
### What Each Tab Does

| Tab | Purpose |
|-----|---------|
| **Overview** | High-level summary of your analysis run, including key KPIs, data quality highlights, and recommended next steps |
| **Key Findings** | Anomalies and issues detected in your data, grouped by type with explanations and suggested actions |
| **Metrics** | Detailed metrics dashboard with trends, drivers, and the ability to explore your data by different dimensions |
| **Profiling & EDA** | Exploratory data analysis including distributions, correlations, and data quality statistics |
| **Ask & Explore** | Query your data using natural language questions — get answers from artifacts or AI-powered insights |
| **Summary Report** | Generate a downloadable summary combining key insights from all tabs |
"""

HOW_TO_READ = """
### How to Read the Outputs

**Severity Indicators:**
- 🔴 **Critical** — Requires immediate attention; significant deviation from expected values
- 🟠 **Warning** — Notable issue that should be reviewed
- 🔵 **Info** — Informational finding for awareness

**Key Metrics:**
- **Units** — Quantity of items sold or processed
- **Sales** — Revenue generated (in dollars)
- **Profit** — Net earnings after costs
- **Profit Margin** — Ratio of profit to sales (percentage)

**Data Quality:**
- Missing values, skewed distributions, and high-cardinality fields are flagged for review
- Correlations help identify relationships between variables
"""

GET_STARTED = """
### Get Started

1. **Select a Project** from the sidebar to choose which analysis to explore
2. **Select a Run** to view a specific analysis snapshot
3. **Navigate the tabs** to explore different aspects of your data

👉 **Ready?** Click on the **Overview** tab to see a summary of your selected analysis run.
"""

ABOUT_ENGINE = """
---
*Powered by the Analyst Agent engine — a policy-driven, deterministic analytics system. 
All outputs are reproducible and auditable.*
"""
